//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.SportTracks.AttackPoint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GK.SportTracks.AttackPoint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string AdvancedFeaturesDisabled {
            get {
                return ResourceManager.GetString("AdvancedFeaturesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string AdvancedFeaturesEnabled {
            get {
                return ResourceManager.GetString("AdvancedFeaturesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status unknown.
        /// </summary>
        internal static string AdvancedFeaturesUnknown {
            get {
                return ResourceManager.GetString("AdvancedFeaturesUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and/or password are not configured for AttackPoint website. Please set up your account in the &quot;Settings&quot; menu first..
        /// </summary>
        internal static string Error_ApCredentialsNotSpecified {
            get {
                return ResourceManager.GetString("Error_ApCredentialsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find category in AP&apos;s mapping configuraion.\nPlease visit AP plugin&apos;s settings..
        /// </summary>
        internal static string ExportError_CategoryNotFound {
            get {
                return ResourceManager.GetString("ExportError_CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is not mapped to any AP&apos;s activity type.\nPlease visit AP plugin&apos;s settings..
        /// </summary>
        internal static string ExportError_CategoryNotMapped {
            get {
                return ResourceManager.GetString("ExportError_CategoryNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export when a date is not specified.\nPlease specify the date for this activity..
        /// </summary>
        internal static string ExportError_DateNotSpecified {
            get {
                return ResourceManager.GetString("ExportError_DateNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export training.\nDistance must be specified for training..
        /// </summary>
        internal static string ExportError_DistanceNotSpecified {
            get {
                return ResourceManager.GetString("ExportError_DistanceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find equipment in AP&apos;s mapping configuraion.\nPlease visit AP plugin&apos;s settings..
        /// </summary>
        internal static string ExportError_EquipmentNotFound {
            get {
                return ResourceManager.GetString("ExportError_EquipmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The equipment item is not mapped to any AP shoes.\nDo you still want to proceed with export?.
        /// </summary>
        internal static string ExportError_EquipmentNotMapped {
            get {
                return ResourceManager.GetString("ExportError_EquipmentNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find intensity in AP&apos;s mapping configuraion.\nPlease visit AP plugin&apos;s settings..
        /// </summary>
        internal static string ExportError_IntensityNotFound {
            get {
                return ResourceManager.GetString("ExportError_IntensityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training&apos;s intensity is not mapped to any AP&apos;s intensity.\nPlease visit AP plugin&apos;s settins page..
        /// </summary>
        internal static string ExportError_IntensityNotMapped {
            get {
                return ResourceManager.GetString("ExportError_IntensityNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export a training when the total time is not specified.\nUse &apos;Export Note instead..
        /// </summary>
        internal static string ExportError_TimeNotSpecified {
            get {
                return ResourceManager.GetString("ExportError_TimeNotSpecified", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon FavIcon {
            get {
                object obj = ResourceManager.GetObject("FavIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_Export {
            get {
                object obj = ResourceManager.GetObject("Image_16_Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttackPoint Plugin.
        /// </summary>
        internal static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
    }
}
